import sys
import os

# Add the project root to sys.path so we can import agents.staging_store
sys.path.append(os.getcwd())

from agents.staging_store import stage_pending_doc_update
from integrations.slack_client import send_approval_request

TEST_PR = 999

def stage_test_data():
    print(f"[*] Staging test data for PR #{TEST_PR}...")
    
    # 1. Stage a new page creation
    stage_pending_doc_update(TEST_PR, "create_or_update_page", {
        "title": "Test Doc: New API Overview",
        "body_markdown": "# Overview\nThis is a test page generated by DocuSync to verify Slack notifications."
    })
    
    # 2. Stage an update to an existing page (dummy ID)
    stage_pending_doc_update(TEST_PR, "update_page", {
        "page_id": "12345",
        "title": "Existing Doc: Configuration Guide",
        "body_markdown": "## Update\nAdded a section on HITL approval workflow.",
        "current_version": 1
    })
    
    print(f"[+] Success! Staged 2 documentation updates in SQLite for PR #{TEST_PR}.")
    
    # 3. Trigger a real Slack notification (Feature 5 verification)
    print(f"[*] Sending real Slack approval request (Feature 5 verification)...")
    send_approval_request(
        pr_number=TEST_PR,
        pr_title="Add new Authentication Middleware",
        summary="Introduces a new JWT-based authentication layer and updates the configuration docs.",
        impact="Changes how all API requests are authorized.",
        risk="High - breaking change if not configured correctly.",
        staging_count=2,
        classification_label="functionality_changed",
        classification_confidence="high"
    )
    
    print(f"[+] Slack notification sent!")
    print(f"[!] Now visit one of these URLs in your browser to approve/reject:")
    print(f"    - Preview: http://localhost:8000/preview/{TEST_PR}")
    print(f"    - Approve: http://localhost:8000/approve/{TEST_PR}")
    print(f"    - Reject:  http://localhost:8000/reject/{TEST_PR}")

if __name__ == "__main__":
    stage_test_data()
